Repository googleapis/python-kms, pull requests merged in 2020-08, with the labels that each got.

#35 docs: Generate using new common.py_samples() synthtool functionality
  .repo-metadata.json
  samples/snippets/README.md
  samples/snippets/README.rst
  samples/snippets/README.rst.in
  synth.py
Labels: cla: yes

#38 test: add system test back
  tests/system/test_system.py
Labels: api: cloudkms, cla: yes

#39 fix: add system test back
  tests/system/test_system.py
Labels: cla: yes

#41 feat: accept custom client_info
  google/cloud/kms_v1/proto/resources.proto
  google/cloud/kms_v1/proto/service.proto
  google/cloud/kms_v1/services/key_management_service/async_client.py
  google/cloud/kms_v1/services/key_management_service/client.py
  google/cloud/kms_v1/services/key_management_service/transports/base.py
  google/cloud/kms_v1/services/key_management_service/transports/grpc.py
  google/cloud/kms_v1/services/key_management_service/transports/grpc_asyncio.py
  google/cloud/kms_v1/types/resources.py
  google/cloud/kms_v1/types/service.py
  scripts/fixup_kms_v1_keywords.py
  synth.metadata
  tests/unit/gapic/kms_v1/test_key_management_service.py
Labels: api: cloudkms, cla: yes, context: partial

#42 chore: update templates
  .gitignore
  .kokoro/build.sh
  .kokoro/docker/docs/Dockerfile
  .kokoro/docker/docs/fetch_gpg_keys.sh
  .kokoro/docs/common.cfg
  .kokoro/docs/docs-presubmit.cfg
  .kokoro/publish-docs.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  docs/conf.py
  noxfile.py
  samples/snippets/README.md
  synth.metadata
Labels: api: cloudkms, automerge, cla: yes, context: partial

#45 docs: add crypto_key_path_path method rename to UPGRADING.md
  UPGRADING.md
Labels: api: cloudkms, automerge, cla: yes
