Repository googleapis/python-kms, pull requests merged in 2021-04, with the labels that each got.

#95 chore: fix --fail-under
  noxfile.py
  synth.metadata
Labels: api: cloudkms, cla: yes, context: none

#97 chore: prevent normalization of semver versioning
  setup.py
Labels: api: cloudkms, cla: yes

#99 Add script to verify attestations with certificate chains
  samples/attestations/verify_attestation_chains.py
  samples/attestations/verify_attestation_chains_test.py
Labels: api: cloudkms, cla: yes

#100 chore(revert): revert preventing normalization
  setup.py
Labels: api: cloudkms, automerge, cla: yes
